services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: ecommerce
        container_name: ecommerce_app
        ports:
            - "${APP_PORT:-80}:80"
        volumes:
            - ".:/var/www/html"
        depends_on:
            - mysql
    mysql:
        image: mysql
        container_name: ecommerce_mysql
        command: "--default-authentication-plugin=mysql_native_password"
        restart: always
        ports:
            - "${FORWARD_DB_PORT:-3306}:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
        volumes:
            - "mysql_data:/var/lib/mysql"
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - "-p${DB_PASSWORD}"
            retries: 3
            timeout: 5s
    phpmyadmin:
        image: phpmyadmin
        container_name: ecommerce_phpmyadmin
        restart: always
        links:
            - mysql
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        ports:
            - "${PHPMYADMIN_PORT:-8080}:80"
volumes:
    mysql_data:
